(function(){if(!google.nocsixjs&&google.timers&&google.timers.load.t)google.timers.load.t.xjses=(new Date).getTime();})();
(function(){google.isOpera=false;google.isIE=false;google.isSafari=true;
google.xhr=function(){var a=null;try{a=new XMLHttpRequest}catch(d){}return a};
google.getComputedStyle=function(a,d,b){var c=b?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");if(!e)return c;c=e.getPropertyValue(d);c=b?c:parseInt(c,10);return c};google.getHeight=function(a){return google.getComputedStyle(a,"height")};google.getWidth=function(a){return google.getComputedStyle(a,"width")};google.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.getPageOffsetTop(a.offsetParent):0)};
google.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?google.getPageOffsetLeft(a.offsetParent):0)};google.getPageOffsetStart=function(a){return google.getPageOffsetLeft(a)};google.getColor=function(a){return google.getComputedStyle(a,"color",true)};google.rhs=function(){};var f,g=location;
google.nav=function(a,d){try{var b=location.protocol+"//"+location.host;if((new RegExp("^("+b+")?/url\\?.*&rct=j(&|$)")).test(a))if(d){google.r=1;d.location.replace(a)}else{if(!f){f=document.createElement("iframe");f.style.display="none";google.append(f)}google.r=1;f.src=a}else g.href=a}catch(c){g.href=a}};google.append=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)};google.bind=function(a,d,b){a.addEventListener(d,b,false);};window.google.unbind=function(a,d,b){a.removeEventListener(d,b,false);};})();
(function(){var c=window,f=Object,h=google,i="push",j="length",k="propertyIsEnumerable",l="prototype",m="call";
function n(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof f)&&f[l].toString[m](a)=="[object Array]"||typeof a[j]=="number"&&typeof a.splice!="undefined"&&typeof a[k]!="undefined"&&!a[k]("splice"))return"array";if(!(a instanceof f)&&(f[l].toString[m](a)=="[object Function]"||typeof a[m]!="undefined"&&typeof a[k]!="undefined"&&!a[k]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[m]=="undefined")return"object";return b}
function o(a){return(new p).serialize(a)}function p(){}p[l].serialize=function(a){var b=[];this.a(a,b);return b.join("")};p[l].a=function(a,b){switch(typeof a){case "string":this.b(a,b);break;case "number":this.d(a,b);break;case "boolean":b[i](a);break;case "undefined":b[i]("null");break;case "object":if(a==null){b[i]("null");break}if(n(a)=="array"){this.c(a,b);break}this.e(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var q={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},r=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;p[l].b=function(a,b){b[i]('"',a.replace(r,function(g){if(g in q)return q[g];var d=g.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return q[g]=e+d.toString(16)}),'"')};p[l].d=function(a,b){b[i](isFinite(a)&&!isNaN(a)?a:"null")};
p[l].c=function(a,b){var g=a[j];b[i]("[");for(var d="",e=0;e<g;e++){b[i](d);this.a(a[e],b);d=","}b[i]("]")};p[l].e=function(a,b){b[i]("{");var g="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b[i](g);this.b(d,b);b[i](":");this.a(e,b);g=","}}b[i]("}")};c.google.stringify=o;if(c.JSON&&c.JSON.stringify&&navigator.userAgent.indexOf("Chrome")==-1)c.google.stringify=c.JSON.stringify;h.History={};var s=[],t="/";h.History.client=function(a){s[i](a);return s[j]-1};var u,v;function w(){var a=u.value;v=a?eval("("+a+")"):{}}function x(a,b){w();v[t]||(v[t]={});v[t][a]=b;u.value=h.stringify(v)}function y(a,b){return function(){x(a,b)}}var z=[];function A(){for(var a=0,b;b=z[a++];)b();z=[]}h.History.save=function(a,b){u?x(a,b):z[i](y(a,b))};
h.History.initialize=function(a){t=a;v=null;if(u=document.getElementById("hcache")){w();for(a=0;a<s[j];++a)v&&v[t]&&v[t][a]&&s[a][m](null,v[t][a]);A()}};})();
(function(){var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":google.isIE?"":0}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.bind(window,"resize",google.rhs);google.rein.push(e);})();
(function(){var f=0,g=[];google.fx={};google.fx.linear=function(a){return a};google.fx.easeOut=function(a){return 1-Math.pow(1-a,3)};google.fx.easeInAndOut=function(a){return(3-2*a)*a*a};google.fx.animate=function(a,d,e){for(var c=0,b;b=d[c++];){b[5]=b[5]==null?"px":b[5];b[4]=b[4]||google.fx.linear;h(b[0],b[1],b[2]+b[5])}g.push({b:a,a:e,d:google.time(),c:d});f=f||window.setInterval(i,15)};function i(){for(var a=0,d;d=g[a++];)j(d)||g.splice(--a,1);if(!g.length){window.clearInterval(f);f=0}}
function j(a){var d=google.time()-a.d;if(d>=a.b){for(var e=0,c;c=a.c[e++];)h(c[0],c[1],c[3]+c[5]);a.a&&a.a();return 0}else{for(e=0;c=a.c[e++];){var b=c[2]+(c[3]-c[2])*c[4](d/a.b);if(c[5]=="px")b=Math.round(b);h(c[0],c[1],b+c[5])}return 1}}
function h(a){for(var d=1;d<arguments.length;d+=2){var e=arguments[d],c=arguments[d+1],b=a.style;if(b&&e in b)b[e]=c;else if(e in a)a[e]=c;}return a}
google.fx.wrap=function(a){var d=document.createElement("div");a.parentNode.replaceChild(d,a);d.appendChild(a);return d};google.fx.unwrap=function(a){a.parentNode.parentNode.replaceChild(a,a.parentNode)};google.dstr.push(function(){window.clearInterval(f);f=0;g=[]});})();
(function(){var f=true,j=null,k=false,l=window.google.ac={},aa=k,m,ba,ca,da,ea,n,fa,ga,p,q,ha,r="",ia=j,s=j,u=j,v=-1,w,x,z,A,C,D,E,G,H,ja,la={},ma,I=0,J=0,na=k,K=j,N=0,oa,pa;var O;
var S;function ua(a){return(a=a&&a.match(/\D+$/))?a[0]:j}var T;
function va(){if(C){wa();V();C.value=D.value=E.value=H.value=G.value="";window.clearTimeout(ia);r=pa=ma="";ia=s=u=j;v=-1;T=I=J=N=0;la={};O=0;}}
function xa(a,b,c,d,e,g){w=a;x=b;q=ha=p=x.value;if(!b.init){oa=document.getElementsByTagName("head")[0];google.bind(w,"submit",ya);x.setAttribute("autocomplete","off");google.bind(x,"blur",V);google.bind(x,"keydown",za);x.onkeyup=Aa;x.setAttribute("spellcheck",k);C=W("aq","f");D=W("aqi","");E=W("aql","");H=W("oq",q);G=W("gs_rfai","");z=document.createElement("table");z.cellSpacing=z.cellPadding="0";A=z.style;z.className="gac_m";w.appendChild(z);
b.init=f}V();Ba();if(!aa){Ca();aa=f}T=0;a="hp";if(c=="i"){T=2;a="img"}else if(d&&d!=""){T=1;a="serp"}a="&client="+a;c=c?"&ds="+c:"";e=e?"&tok="+encodeURIComponent(e):"";d=["?hl=",google.kHL,a,Da(),c,(d?"&pq="+encodeURIComponent(d):""),e].join("");ma="/complete/search"+d;pa="/complete/deleteitems"+
d;O=Ea(x);Ga();Ha();g&&Ia(g);Ja();ga=["http",fa?"s":"","://"].join("");(new Image).src=ga+"clients1.google.ru/generate_204";
}
function Ca(){function a(d,e){b.push(d,"{",e,"}")}var b=[];a(".gac_m","cursor:default;line-height:117%;border:1px solid #666;z-index:99;background:white;position:absolute;margin:0;font-size:17px");a(".gac_m td","line-height:22px");a(".gac_n","padding-top:1px;padding-bottom:1px");a(".gac_b td.gac_c","background:#d5e2ff");a(".gac_b","background:#d5e2ff");a(".gac_a td.gac_f","background:#fff8dd");
a(".gac_p","padding:1px 4px 2px 3px");a(".gac_u","padding:0 0 1px 0;line-height:117%;text-align:left");a(".gac_t","width:100%;text-align:left;font-size:17px");a(".gac_bt","width:"+(x.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px");a(".gac_sb","font-size:15px;height:28px;margin:0.2em"+";-webkit-appearance:button");a(".gac_z","white-space:nowrap;color:#c00");a(".gac_s","height:3px;font-size:1px");var c="white-space:nowrap;overflow:hidden;text-align:left;padding-left:3px;padding-right:3px";a(".gac_c",c);a(".gac_e","text-align:right;padding:0 3px");a(".gac_d","font-size:11px");a(".fl,a:link.fl,a:visited.fl","color:#77c");a(".gac_h","color:green");a(".gac_j","display:block");a(".gac_l","line-height:18px");a(".gac_x","display:block;line-height:16px");a(".gac_y","font-size:13px");a(".gac_i","color:#666");a(".gac_w img","width:40px;height:40px");a(".gac_w","width:1px");a(".gac_r","color:red");a(".gac_v","padding-bottom:5px");c=document.createElement("style");c.setAttribute("type","text/css");oa.appendChild(c);b=b.join("");c.appendChild(document.createTextNode(b));}
function Ba(){if(z){var a=Ka(x);A.left=a.F+"px";A.top=a.H+x.offsetHeight-1+"px";A.width=x.offsetWidth+"px";}}function Ka(a){for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}return{H:b,F:c}}function W(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return w.appendChild(c)}
function za(a){var b=a.keyCode;if(b==27&&La()){V();X(q);a.cancelBubble=f;return a.returnValue=k}if(b==13){Ma(k);a.cancelBubble=f;return a.returnValue=k}if(b==38||b==40){J++;J%3==1&&Fa(b);a.cancelBubble=f;a.returnValue=k;return k}}
function Ma(a){if(!a&&ja){w.removeChild(ja);ja=j}if(u&&v!=-1&&na&&!(a&&u.D))u.onclick(j);else if(x.value=="")V();else{if(a)ja=W("btnI","1");Na()}}function Na(){ya();w.onsubmit&&w.onsubmit()==k||w.submit()}function Aa(a){a=a.keyCode;if(!J)Fa(a);J=0;return !(a==38||a==40)}
function Fa(a){if(x.value!=p){q=x.value;O=Ea(x);H.value=q}if(a==40||a==38){Oa(a==40);na=La()}Ba();if(r!=q&&!K)K=window.setTimeout(V,500);p=x.value}
function Pa(){na=k;if(!N){if(u)u.className="gac_a";u=this;for(var a=0,b;b=Y(a);a++)b==u&&(v=a);u.className="gac_b"}}function Qa(a,b){return function(){Ra(Sa(a),b);return k}}function Sa(a){return[a,"&aq=",u.t,"&oq=",H.value,Z("aqi",D),Z("aql",E),Z("gs_rfai",G)].join("")}
function Z(a,b){if(b&&b.value.length&&a.length)return["&",a,"=",b.value].join("");return""}function Ra(a,b){var c=window.frames.wgjf;if(c&&!b){google.r=1;c.location.replace(a)}else window.location=a}
function Ta(){X(this.j);Na();}
function Oa(a){if(!(q!=r||!s||!s.length))if(La()){if(u)u.className="gac_a";for(var b=s.length,c=(v+1+(a?1:b))%(b+1)-1;c!=-1&&Y(c).z;)c=(c+1+(a?1:b))%(b+1)-1;v=c;if(v==-1)Ua();else{u=Y(c);u.className="gac_b";X(u.j);C.value=u.t}}else Va()}function Ua(){x.focus();X(q);u=j;C.value="f"}function V(){if(K){window.clearTimeout(K);K=j}A&&(A.visibility="hidden");}
function Va(){A&&(A.visibility="visible");Ba();N=1}function La(){return!!A&&A.visibility=="visible"}function wa(){if(z){z.innerHTML="";}}
function Wa(a,b,c){a.onclick=b?Qa(b,c):Ta;a.D=!b;a.onmousedown=Xa;a.onmouseover=Pa;a.onmousemove=function(){if(N){N=0;Pa.call(this)}}}function Ya(a,b){Za(a);a=0;for(var c;c=Y(a++);)if(c.t==b){$a(pa,"delq",c.j,ab);break}return k}function ab(a){for(var b=0,c;c=Y(b++);)if(ua(c.t)=="p"&&c.j==a[0]){c.z=1;c.onclick=c.onmouseover=j;if(c==u){c.className="gac_a";v=-1;Ua()}c.A.className="gac_c gac_i fl";c.A.innerHTML="Этот запрос был удален из вашей \x3ca href\x3d\x22/history\x22\x3eистории веб-поиска\x3c/a\x3e"}}
function bb(a){function b(ka,U){U=U?ua(U[2]):j;ka=ka+(U?"-"+U:"");if(ka!=g){if(h)e+=g+h;h=0;g=ka}h++;d++}var c=a[0];I>0&&I--;if(!(!z||c!=q)){if(K){window.clearTimeout(K);K=j}r=a[0];wa();var d=0,e="",g,h=0;c=a[1];for(var i=c.length-1,t=0,o,L,M,y,F,B;t<=i;t++)if(B=c[t])if(y=la[B[1]]){y.B&&y.B(t,i)&&cb();o=B[2];L=B[3];M=y.g?y.g(B,L):j;F=z.insertRow(-1);Wa(F,M,y.C);F.t=o;F.className="gac_a";M=F.A=document.createElement("td");M.className=
"gac_c";y.e(M,o,B,L);o=y.w;F.j=o?o(B,L,r):B[0];F.appendChild(M);b(y.b,B);t<i&&y.G&&cb()}E.value=a[3]||"";G.value=a[4]||"";if(d>0){T==0&&eb();Va()}else V();b("");D.value=e;v=-1;s=z.rows;(s&&s.length>0?Va:V)()}}
function Y(a){b=s.item(a);return b}
function eb(){var a=z.insertRow(-1);a.z=1;a.onmousedown=Xa;a=a.insertCell(0);a.innerHTML='<div class=gac_bt><input class=gac_sb type=button value="Поиск в Google" onclick="google.ac.rd(0)"><input class=gac_sb type=button value="Мне повезёт!" onclick="google.ac.rd(1)"></div>'}function fb(a){return a.replace(/<\/?[b|em]>/gi,"")}
function $(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}function gb(a,b,c){m=k;if(a.which)m=a.which==2;else if(a.button)m=a.button==4;b.href=Sa(c)}function hb(a){if(m){Za(a);return f}return k}
function Za(a){a.stopPropagation();a.cancelBubble=a.cancel=a.returnValue=f}
function cb(){var a=z.insertRow(-1);a.z=1;a.onmousedown=Xa;a.insertCell(0).className="gac_s"}function ya(){V();if(s&&Y(v)&&H.value!=x.value)C.value=Y(v).t;else{H.value="";C.value="f";if(I>=10)C.value="o"}}function Ga(){if(q&&ha!=q){I++;$a(ma,"q",q,bb);x.focus()}ha=q;for(var a=100,b=1;b<=(I-2)/2;b++)a*=2;a+=50;ia=window.setTimeout(Ga,a)}
function $a(a,b,c,d){S&&oa.removeChild(S);S=document.createElement("script");S.src=[ga,"clients1.google.ru",a,"&",b,"=",encodeURIComponent(c),"&cp="+O].join("");oa.appendChild(S);}function X(a){if(x)x.value=p=a}function db(a,b){a.appendChild(document.createTextNode(b))}
function Xa(a){a.stopPropagation();return k}
function Ea(a){var b=0,c=0;if(lb(a)){b=a.selectionStart;c=a.selectionEnd}return b&&c&&b==c?b:0}function lb(a){try{return typeof a.selectionStart=="number"}catch(b){return k}}
function mb(a){var b=[];a=a.replace(/\s+<\/b>/g,"</b> ");var c=q.replace(/^\s+/,"").replace(/\s{2,}/g," ").split(" "),d=a.split(" ");a=fb(a).split(" ");for(var e={q:"",v:0,k:0,m:0},g,h,i;e.m<a.length;++e.m){i=d[e.m];if(e.k==c.length)b.push(i," ");else{g=c[e.k];h=a[e.m];if(g==h){++e.k;b.push(i," ")}else{nb(g,h,c,a,e,f,d);g=e.k==c.length;b.push(ob(e.v,g,i,e.q,"<b><i>","</i></b>"))}}}return pb(b.join(""))}
function ob(a,b,c,d,e,g){d=d&&d.length?pb(d):c;if(a==1&&b)return d+" ";return[e,d,g," "].join("")}function nb(a,b,c,d,e,g,h){e.k=qb(b,c,e.k,e,!g);if(e.v==0){e.m=qb(a,d,e.m,e,g,h);++e.k;e.v>0&&--e.m}}function qb(a,b,c,d,e,g){d.q=[];for(var h=d.v=0,i=a.length,t=b.length,o=b[c];h<i&&rb(a.substr(h),o);){if(e)d.q.push(g?g[c]:o," ");++d.v;h+=o.length;if(++c==t)break;o=b[c]}d.q=d.q.join("");return c}function rb(a,b){return a.substr(0,b.length)==b}
function pb(a){var b=a.length-1;return a.substr(b)==" "?a.substring(0,b):a}function Ha(){ba=f;ca=k;da=f;ea=k;n=f;fa=k}function Ia(a){if("a"in a)ba=a.a;if("l"in a)ca=a.l;if("n"in a)da=a.n;if("o"in a)ea=a.o;if(T==2)n=k;else if("p"in a)n=a.p;if("s"in a)fa=a.s}function Ja(){var a=[sb];ba&&a.push(tb);ca&&a.push(ub);da&&a.push(vb);ea&&a.push(wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb);Gb(a)}function Gb(a){for(var b=0,c;c=a[b++];)la[c.f]=c}
var tb={f:8,b:"a",G:f,w:function(a,b,c){return c},g:function(a,b){return b[1]+Da()},B:function(a,b){return a==b},e:function(a,b,c,d){b=d[0];var e=d[1]+Da();c=d[2];var g=d[3];d=d[4];a.className="gac_f gac_p";var h=fb(b);e=$("http://"+h,e);a.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td><table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td style="line-height:117%;vertical-align:bottom"><a class=q ',e,">",c,'</a><td class="gac_e gac_d gac_i">Рекламная ссылка</table><tr><td class="gac_u gac_x gac_y" style="line-height:16px;padding-bottom:8px"><span class=gac_h',">",b,"</span>&nbsp; &nbsp;",g,d?" "+d:"","</table>"].join("")}},Bb={f:11,b:"b",C:f,g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2],g=d[3],h=d[4],i=d[5],t=d[6];d=d[7];var o=b.match(/^([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a class=q ',$(o,b),"><b>",c,"</b> - ",e," (",g,")</a><br><b>",h,"</b> <span class=gac_y><span class=gac_",i>=0?"h":"r",">",i," (",t,"%)</span> ",d,' - </span><a href=/help/stock_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a></span>'].join("")}},
Cb={f:12,b:"c",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];for(var e="",g=d.length-1,h=0,i;h<g;h++){i=d[h];e+=[i[0],'<div class="gac_v">',i[1],"</div>"].join("")}i=d[g];e+=[i[0],"<br>",i[1]].join("");Hb(1,a,c,b,"www.flightstats.com",e)}},Db={f:15,b:"d",e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];a.innerHTML=["<b>",b,"</b> ",e," (",c,") in <b>",d,"</b>"].join("")}},Eb={f:13,b:"e",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Hb(1,a,c,b,d)}},
xb={f:14,b:"f",g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];Hb(1,a,c,b,d,e)}},sb={f:0,b:"g",w:function(a){return a.j},e:function(a,b,c){var d=c[0];a.innerHTML=d;c.j=a.textContent;if(n&&ua(b)=="p"){a.className="";a.innerHTML=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td class=gac_c>",
d,'<td class="gac_d gac_e fl"><a href=# onclick="return google.ac.dc(event,\'',b,"')\">Удалить</a></table>"].join("");}}},yb={f:19,b:"h",e:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,"</b>"].join("")}},wb={f:17,b:"i",g:function(a,b){return b[3]},e:function(a,b,c,d){b=d[0];
c=d[1];var e=d[2];d=d[3];var g=d.match(/url=([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a ',$(g,d),">",b," &#151; ",c,": ",e,'</a><span class=gac_y style="line-height:16px"><br>According to <span class=gac_h>',g,"</span></span></span>"].join("")}},Fb={f:10,b:"j",e:function(a,b,c,d){b=d[0];c=d[1];var e=d[4];d=d[5];var g=function(h){var i=h[0],t=h[1],o=h[2],L=h[3];h=h[4];return['<td class=gac_w><img src="',i,'" alt="',t,'" title="',t,'"><td class="gac_c" style="line-height:112%;vertical-align:top">',
h,"<br>",o,"&deg; | ",L,"&deg;"].join("")};a.innerHTML=["<b>Weather:</b> ",e,"&deg;",c," in ",b,"<br><table class=gac_t><tr>",g(d[0]),g(d[1]),g(d[2]),g(d[3]),"</table>"].join("")}},zb={f:20,b:"k",e:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,'</b> - <a href=/intl/en/help/currency_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a>'].join("")}},Ab={f:16,b:"l",w:function(a,b){return"define: "+b[0]},e:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Hb(1,a,
"Web definitions for <b>"+b+"</b>","/search?q=define:"+b.replace(" ","+"),"www.google.com",[c," - <span class=gac_i>",d,"</span>"].join(""))}},ub={f:30,b:"m",e:function(a,b,c){a.innerHTML=["<span class=gac_z>Did you mean: </span>",mb(c[0])].join("")}},vb={f:5,b:"n",w:function(a,b,c){return c},g:function(a,b){return b[0]},e:function(a,b,c,d){b=d[0];d=d[1];a.className="gac_c gac_n";a.style.lineHeight="117%";var e=c[0];c=e.replace(/HTTPS?:\/\//gi,"");e=fb(e);/^HTTPS?:\/\//i.test(e)||(e=(b.indexOf("/url?url=https:")>
0?"https":"http")+"://"+e);b=$(e,b);a.innerHTML=["<span class=gac_x><a ",b,">",d,'</a><br><span class="gac_h gac_y"',">",c,"</span></span>"].join("");}};
function Hb(a,b,c,d,e,g,h){var i=d.indexOf("/url")?d:d.match(/url=([^&]*)/)[1];b.style.lineHeight="112%";b.innerHTML=["<a class=q ",$(i,d),">",c,'</a><span class="gac_y'+(a?" gac_x":"")+'">',g?g+"<br>":"",h?h+"<br>":"",e?"<span class=gac_h>"+e+"</span></span>":""].join("")}function Da(){if(google.kEXPI)return"&expIds="+google.kEXPI;return""}l.c=hb;l.d=ab;l.dc=Ya;l.h=bb;l.i=xa;l.p=Za;l.r=gb;l.rd=Ma;l.u=X;google.bind(window,"resize",Ba);google.dstr&&google.dstr.push&&google.dstr.push(va);})();
(function(){window.ManyBox={};var d,g,i=1,l=google.History.client(j);function m(a){for(var b in d)if(d[b].c&&a(d[b]))return}function n(a,b,c,e,f){this.c=a;this.i=b;this.B=e;this.o=f;this.q="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+e+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.l="";g[a]={r:0,D:this.e,i:this.i,h:0};this.n=0}n.prototype.append=function(a){this.l+="&"+a.join("&")};
function o(a,b){a.g.style.paddingTop=b+"px";a.g.style.display=a.g.innerHTML?"":"none";if(b>a.n)a.n=b}
function q(a){if(!a.A){a.A=1;a.d=document.getElementById("mbb"+a.c);a.j=0;a.a=document.getElementById("mbl"+a.c);a.m=a.a.getElementsByTagName("DIV")[0];a.p=a.a.getElementsByTagName("A")[0];a.z=a.p.innerHTML;a.o=a.o||a.z;a.m.title="Нажмите, чтобы получить дополнительную информацию";a.a.F=function(b,c){var e=google.getPageOffsetStart(a.a),f=google.getPageOffsetTop(a.a);return b>e-5&&b<e+google.getWidth(a.a)+5&&c>f-5&&c<f+google.getHeight(a.a)+5};a.g=document.getElementById("mbf"+a.c);o(a,0);a.a.onmousedown=r(a);a.a.onclick=s(a);a.a.go=
function(){a.a.onmousedown();a.a.onclick()}}}function t(a){google.log("manybox",[a.j?"close":"open","&id=",a.c,"&docid=",a.i,"&mbtype=",a.B,a.l].join(""))}
function r(a){return function(){if(g[a.c].h)a.I++<3&&t(a);else{if(a.e.k)t(a);else{var b=google.xhr();if(b){b.open("GET",a.q+a.l+"&zx="+google.time());a.t=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(e){}if(!c&&!a.C){g[a.c].h=0;a.C=1;a.q+="&cad=retry";a.a.onmousedown()}else{a.u&&u(a);a.t=0}}};a.t=1;b.send(null)}}g[a.c].h=a.I=1}}}function s(a){return function(){g[a.c].h||a.a.onmousedown();(a.u=a.t)||u(a)}}
function v(a){if(!a.e.k){a.e.k="\x3cfont color\x3dred\x3eОшибка.\x3c/font\x3e Серверу не удалось выполнить ваш запрос. Повторите попытку через 30 секунд.";a.G=a.a.onclick;a.a.onclick=function(){i=0;u(a);i=1;a.b.parentNode.removeChild(a.b);g[a.c].h=a.e.k=a.v=0;a.a.onclick=a.G}}if(!a.v){a.v=1;var b=document.getElementById("res");a.H=b&&google.getPageOffsetStart(a.d)>google.getPageOffsetStart(b)+google.getWidth(b);a.b=document.createElement("div");o(a,0);a.b.style.position="absolute";a.b.style.paddingTop=a.b.style.paddingBottom="6px";a.b.style.display="none";a.b.className="med";b=document.createElement("div");
a.b.appendChild(b);b.className="std";b.innerHTML=a.e.k;a.g.parentNode.insertBefore(a.b,a.g)}}function j(a){i=0;ManyBox.init();m(function(b){if(b.i==a[b.c].i){b.e=a[b.c].D;a[b.c].r!=b.j&&u(b)}else a[b.c].h=0});g=a;i=1;google.History.save(l,g)}ManyBox.create=function(a,b,c,e,f){return new n(a,b,c,e,f)};ManyBox.register=function(a,b,c,e,f){return d[a]=ManyBox.create(a,b,c,e,f)};
google.bind(document,"click",function(a){a=a||window.event;for(var b=a.target||a.srcElement;b.parentNode;){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}m(function(c){if(c.a.F(a.clientX,a.clientY)){c.a.go();return 1}})});function w(){d={};g={};history.navigationMode=history.navigationMode&&"fast"}w();ManyBox.init=function(){m(q)};function x(a,b){a.b.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}n.prototype.insert=function(a){this.e.k=a};
function y(a){a.f=document.getElementById("mbcb"+a.c);var b=a.f&&a.f.getAttribute("mbopen");if(b){eval(b);a.onopen(a.f)}}function z(a){a.b.style.display="none";a.m.style.backgroundPosition="-91px -74px";a.p.innerHTML=a.z;a.j=g[a.c].r=0;google.History.save(l,g)}
function A(a,b,c,e,f){var k=c>0?150:75,h=google.time()-f;k=h<k&&i?h/k*c:e>1?c-10:c;h=Math.max(a.s,b+k);var p=h-a.s;x(a,p);a.d.style.height=h<0?0:p?h+"px":"";o(a,Math.max(0,p-5));google.rhs();Math.abs(k)<Math.abs(c)?window.setTimeout(function(){A(a,b,c,e-1,f)},30):window.setTimeout(function(){c<0?z(a):y(a);if(!google.isIE&&a.H)a.b.style.width="100px";a.b.style.position=a.d.style.height="";o(a,0);google.rhs();a.d.w=0},0)}
function u(a){a.u=0;if(!a.d.w){a.d.w=1;var b;if(a.j){if(b=a.f&&a.f.getAttribute("mbclose")){eval(b);a.onclose(a.f)}b=a.s-google.getHeight(a.d);a.g.style.display="none";o(a,a.n);a.b.style.position="absolute"}else{a.s=google.getHeight(a.d);v(a);o(a,0);a.n=0;m(function(c){c.m.title=""});a.m.style.backgroundPosition="-105px -74px";a.p.innerHTML=a.o;x(a,1);a.b.style.position="absolute";a.b.style.display="";a.j=g[a.c].r=1;google.History.save(l,g);b=a.b.offsetHeight}A(a,google.getHeight(a.d),b,google.isSafari?
2:1,google.time())}}google.dstr&&google.dstr.push(w);})();
(function(){var f=true,h=false,i,k;var l;
function m(){i=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(i);k=i.sheet;if(!k){l=document.createTextNode("");i.appendChild(l)}}
google.addCSSRule=function(a,b){i||m();a=a+"{"+b+"}";if(!k){l.data+=a;return}k.insertRule(a,k.cssRules.length);};google.acrs=function(a){a=a.split(/{|}/);for(var b=1;b<a.length;b+=2)google.addCSSRule(a[b-1],a[b])};
var n=null,o=h,p=h,q=document.location.href.match("^.*?://[^/]*")[0],r,s;function t(a,b){s=document.getElementById("tbd");r=s.innerHTML=a;b||google.Toolbelt.toggle(null,null,f);google.j&&google.j.trap&&google.j.trap();google.isr&&google.isr.initialize&&google.isr.initialize()}var u=google.History.client(function(a){t(a.content,a.open==google.Toolbelt.isToolbeltOpen())}),x=google.History.client(function(a){google.acrs(a)});google.Toolbelt.ascrs=function(a){google.acrs(a);google.History.save(x,a)};
var y=[];google.Toolbelt.resetListeners=function(){y=[]};google.Toolbelt.registerToolbeltCallback=function(a){y.push(a)};function z(){for(var a=0,b;b=y[a++];)b()}google.Toolbelt.listeners=function(){return y};var A=/([?&])tbo=([^&]*)(&|$)/;function B(a){return(a=a.match(A))?a[2]:""}function C(a){a=B(a);return mbtb1.obd?a!="0":a!=""&&a!="0"}google.Toolbelt.setCurrentTbo=function(a){return D(a,google.Toolbelt.isToolbeltOpen())};
function D(a,b){var c=mbtb1.obd&&!B(a)?"":"1",d=mbtb1.obd?"0":"";b=b?c:d;return a.replace(A,"$1").replace(/&$/,"")+(b?"&tbo="+b:"")}
google.Toolbelt.updateTbo=function(){var a=google.Toolbelt.isToolbeltOpen();if(a!=C(google.base_href)){var b=document.getElementsByTagName("A");google.base_href=D(google.base_href,a);for(var c=0,d;d=b[c++];)if(d.href.match("^("+q+")?/(?!url|aclk|[^?]*$)")&&d!=n&&!d.href.match("[?&]tbo=u(&|$)")){d.href=D(d.href,a);}for(c=0;b=document.forms[c++];)if(b.action.match("/search$")){e=
d=0;for(var g;g=b.elements[e++];)if(g.name=="tbo"){d=1;if(a)g.value="1";else if(mbtb1.obd)g.value="0";else g.parentNode.removeChild(g)}if(!d){d=document.createElement("input");d.type="hidden";d.value=a?"1":"0";d.name="tbo";b.appendChild(d)}}}};function F(a){document.body.className=document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.Toolbelt.updateTbo();z()}google.Toolbelt.isToolbeltOpen=function(){return/\btbo\b/.test(document.body.className)};
google.Toolbelt.toggle=function(a,b,c){b=b||window.event;if(a)n=a;b&&b.stopPropagation();s=document.getElementById("tbd");if(!s)return f;r=s.innerHTML;b=s.getElementsByTagName("DIV").length>0;var d=google.Toolbelt.isToolbeltOpen();c=c||!!document.getElementById("tbt5")||mbtb1.na;if(d&&!p){google.Toolbelt.updateCalendarVisibility&&google.Toolbelt.updateCalendarVisibility(null);
G(h,c);google.log("toolbelt","0&ei="+google.kEI);o=f}else if(b){G(f,c);o&&google.log("toolbelt","1&ei="+google.kEI)}else{mbtb1.insert=t;var e=google.xhr();if(e){e.open("GET",[google.pageState?google.pageState.replace("#","/mbd?"):google.base_href.indexOf("/images?")==0?google.base_href.replace(/^\/images\?/,"/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""),f);e.onreadystatechange=
function(){if(e.readyState==4&&e.status==200)try{eval(e.responseText)}catch(g){window.location.replace(a.href)}};e.send(null);p=f;G(f,c)}return h}google.History.save(u,{content:r,open:p||!d});p=h;google.isr&&google.isr.handleToolbeltToggle&&google.isr.handleToolbeltToggle();return h};function H(a){for(;a&&!/(^|\s)tbt(\s|$)/.test(a.className);)a=a.parentNode;return a}
google.Toolbelt.ctlClk=function(a,b,c){a=a||"cdr_opt";if(a=="cdr_opt"){c&&c.stopPropagation();}google.Toolbelt.maybeLoadCal&&google.Toolbelt.maybeLoadCal();b=b||"cdr_min";if(a=document.getElementById(a)){a.className="tbots";if(a=H(a)){c=0;for(var d;d=a.childNodes[c++];)if(d.className=="tbos")d.className="tbotu";(b=document.getElementById(b))&&b.focus()}}return h};
google.Toolbelt.cdrClk=google.Toolbelt.ctlClk;function I(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")}google.Toolbelt.cdrSbt=function(){return J("ctbs",{cdr_min:"cd_min",cdr_max:"cd_max"})};google.Toolbelt.clSbt=function(){return J("ltbs",{l_in:"cl_loc"})};google.Toolbelt.prcSbt=function(){J("prcbs",{prc_min:"pr_min",prc_max:"pr_max"});var a=document.getElementById("prc_frm");if(a){var b=document.getElementById("tsf");if(b)a.elements.q.value=b.elements.q.value}};
function J(a,b){if(a=document.getElementById(a))for(var c in b){var d=I(document.getElementById(c).value),e=new RegExp("("+b[c]+":)([^,]*)");a.value=a.value.replace(e,"$1"+d)}return f}google.Toolbelt.tbosClk=function(a){a=a||window.event;if((a=a.target||a.srcElement)&&a.className=="tbotu"){a.className="tbos";if(a=H(a))for(var b=0,c;c=a.childNodes[b++];)if(c.className=="tbots")c.className="tbou"}};
var K=google.fx.easeOut,L=[["tads","margin-left","marginLeft"],["res","margin-left","marginLeft"],["tbd","margin-left","marginLeft"],["mbEnd","width","width"],["tbt3","left","left"],["tbt8","left","left"],["tbt5","margin-left","marginLeft"]],M=h;function N(a){for(var b=0,c=0,d;d=L[c++];){var e=document.getElementById(d[0]);e&&a(e,d,b++)}}function O(){var a=[];N(function(b,c){c=c[1];a.push(c=="width"?b.offsetWidth:google.getComputedStyle(b,c))});return a}
function G(a,b){if(!M){var c=[],d=O(),e=google.getComputedStyle(s,"left",f),g=document.getElementById("cdr_min"),j=document.getElementById("cdr_max");if(g&&j){g.style.width=google.getComputedStyle(g,"width",f);j.style.width=google.getComputedStyle(j,"width",f)}F(a);google.isr&&google.isr.reflowResults&&google.isr.reflowResults();if(!b){if(a){e=google.getComputedStyle(s,"left",f);if(g&&j){g.style.width=google.getComputedStyle(g,"width",f);j.style.width=google.getComputedStyle(j,"width",f)}}var P=O();
N(function(v,w,E){c.push([v,w[2],d[E],P[E],K])});b=google.fx.wrap(s);b.style.position="absolute";b.style.overflow="hidden";b.style.left=e;s.style.display="block";s.style.position="static";M=f;google.fx.animate(a?400:200,c,function(){N(function(v,w){v.style[w[2]]=""});s.style.position="absolute";s.style.display="";google.fx.unwrap(s);if(g&&j){g.style.width="";j.style.width=""}M=h})}}};})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var e=window.gbar,g,k;function l(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(c,d){return(d||"&")+"q="+encodeURIComponent(b)})}e.qs=l;function m(a,b,c,d,j,h){var f=document.getElementById(a),i=f.style;if(f){i.left=d?"auto":b+"px";i.right=d?b+"px":"auto";i.top=c+"px";i.visibility=k?"hidden":"visible";if(j&&h){i.width=j+"px";i.height=h+"px"}else{m(g,b,c,d,f.offsetWidth,f.offsetHeight);k=k?"":a}}}e.tg=function(a){a=a||window.event;var b=a.target||a.srcElement;a.cancelBubble=true;if(g!=null)n(b);else{a=document.createElement(Array.every||window.createPopup?"iframe":"div");a.frameBorder="0";a.src="#";g=b.parentNode.appendChild(a).id="gbs";document.onclick=e.close;n(b);e.alld&&e.alld(function(){var c=document.getElementById("gbli");if(c){var d=c.parentNode;d.removeChild(c);o(d)}})}};function p(a){var b,c=document.defaultView;if(c&&c.getComputedStyle){if(a=c.getComputedStyle(a,""))b=a.direction}else b=a.currentStyle?a.currentStyle.direction:a.style.direction;return b=="rtl"}function n(a){var b=0;if(a.className!="gb3")a=a.parentNode;var c=a.getAttribute("aria-owns")||"gbi",d=a.offsetWidth,j=a.offsetTop>20?46:24,h=false;do b+=a.offsetLeft||0;while(a=a.offsetParent);a=(document.documentElement.clientWidth||document.body.clientWidth)-b-d;d=p(document.body);if(c=="gbi"){var f=document.getElementById("gbi");e.alli&&e.alli(f);o(f);if(d){b=a;h=true}}else if(!d){b=a;h=true}k!=c&&e.close();m(c,b,j,h)}e.close=function(){k&&m(k,0,0)};function q(a,b){var c=a.firstChild?a.firstChild.className:"gb2";a.insertBefore(b,a.firstChild).className=c}function o(a){for(var b,c=window.navExtra;c&&(b=c.pop());)q(a,b)}})();;};
(function(){var f=true,g=false;window.google.rt={};var h,i,j,k,l,m,n,o,p,q,r,s,t,u;function aa(){h=30;i=[];k=j=g;l="";n=0;o=g;p=(new Date).getTime();q=100}google.rt.init=function(a,b,c){aa();if(m=document.getElementById(a)){if(c)if(c.maxResults)q=c.maxResults;document.onmousemove=function(){o=f};document.onkeydown=function(){o=f};b&&v(b);i.length==0&&window.setTimeout(w,3E3);x(w,h);ba(m);if(ca("sbu","sbd","sbb",a)){y.push(function(){k=f});z.push(function(){k=g});A(0,f)}B(C,3E3,6E3)}};
google.rt.pause=function(){D();E();var a=document.getElementById("rth");a=a.getElementsByTagName("span");F(a[0]);G(a[1]);u=(new Date).getTime()};google.rt.resume=function(){var a=((new Date).getTime()-u)/1E3;if(a>10)i=[];w();x(w,h);B(C,2E3,6E3);a=document.getElementById("rth");a=a.getElementsByTagName("span");F(a[1]);G(a[0])};function F(a){a.style.display="none"}function G(a){a.style.display=""}
function x(a,b){var c=b;if(n){c=Math.pow(2,n)*5;c=(Math.random()+0.5)*c;c=Math.min(7200,c)}t=window.setTimeout(function(){a();x(a,b)},c*1E3)}function D(){window.clearTimeout(t)}function B(a,b,c){r=window.setTimeout(function(){a();s=window.setInterval(a,c)},b)}function E(){window.clearTimeout(r);window.clearInterval(s)}
function C(){if(m.getElementsByTagName("li").length>=q){var a=document.getElementById("rth");a=a.getElementsByTagName("span");if(a.length>2){F(a[0]);F(a[1]);G(a[2])}}else if(!(!i.length||k)){a=i.shift();var b=a.getElementsByTagName("li")[0];m.insertBefore(a,m.firstChild);H(b);google.History.save(da,{r:m.innerHTML,u:l,t:I()});var c=-google.getComputedStyle(b,"height")-google.getComputedStyle(b,"margin-bottom");b=m.scrollTop;if(b<20){A(b);a=[[a,"marginTop",c,0,google.fx.easeInAndOut]];google.fx.animate(1200,a)}else A(b-c)}}function v(a){if(a.results)for(var b=a.results.length,c;c=a.results[--b];)i.push(ea(c));if(a.nextRequest)l=a.nextRequest;if(a.pollSeconds)h=a.pollSeconds}window.mbrt0={insert:function(a){a=eval("("+a+")");v(a)}};
function w(){if(o){o=g;p=(new Date).getTime()}else if((new Date).getTime()-p>24E4)return;if(!(j||i.length>=20||!l)){var a=google.xhr();a.open("GET",l);a.onreadystatechange=function(){if(a.readyState==4){if(a.status==200){eval(a.responseText);n=0}else n++;j=g}};j=f;a.send(null)}}function ea(a){var b=document.createElement("div");b.innerHTML=a.html;fa(b);return b}var da=google.History.client(function(a){m.innerHTML=a.r;l=a.u;H(m,f,a.t);A(0,f);i=[];w()});google.dstr.push(function(){E();D()});
var J,K,L,M,N,O,P,y,z,R,S,T=g;function U(a){var b=google.getComputedStyle(a,"height");return b}function V(a){a=a.offsetTop;a-=M.offsetTop;return a}
function W(a){if(a)for(var b=0,c;c=y[b++];)c();else if(P)for(b=0;c=z[b++];)c();P=a}function X(a){var b=ga(a);if(b){var c=V(b);a||(c+=U(b)-S);Y(c,f,300,function(){ha(a)})}}function Y(a,b,c,d){var e=M.scrollHeight-S;e=e==0?0:ia(a*(R-Math.max(S/M.scrollHeight*R,20))/e);e=[[L,"marginTop",google.getComputedStyle(L,"margin-top"),e,google.fx.easeInAndOut]];if(b)e.push([M,"scrollTop",M.scrollTop,a,google.fx.easeInAndOut,""]);else M.scrollTop=a;google.fx.animate(c,e,d)}
function ha(a){setTimeout(function(){P&&X(a)},200)}function ga(a){var b=M.childNodes;if(a)for(a=b.length-1;a>=0;--a){var c=b[a],d=V(c);if(c.nodeType==1&&d<M.scrollTop)return c}else for(a=0;c=b[a++];){d=V(c);if(c.nodeType==1&&d+U(c)>M.scrollTop+S)return c}}function Z(a){var b=a.clientY-N;b=ia(google.getComputedStyle(L,"margin-top")+b);L.style.marginTop=b+"px";M.scrollTop=b*(M.scrollHeight-S)/(R-U(L));N=a.clientY}function ia(a){return Math.max(0,Math.min(R-U(L),a))}
function A(a,b){if(T){var c=U(L),d=Math.max(S/M.scrollHeight*R,20),e=document.getElementById("sbbb");c=[[L,"height",c,d],[e,"marginTop",c-7,d-7]];if(!O){e=d=0;for(var Q;Q=M.childNodes[e++];)if(Q.nodeType==1)d+=U(Q);if(d>S){c.push([document.getElementById("sb"),"opacity",0,1,google.fx.linear,""]);O=f}}b=b?0:1200;Y(a,g,b);google.fx.animate(b,c,function(){L.style.position="absolute"})}}
function $(a,b){if(a.parentNode==L)a=L;b=70*(b?1:-1);ja(a,b);for(var c=0,d;d=a.childNodes[c++];)d.nodeType==1&&ja(d,b)}function ja(a,b){var c=a.style.backgroundPosition.match(/^-?\d+/),d=a.style.backgroundPosition.match(/\s+.*$/);a.style.backgroundPosition=parseInt(c,10)+b+"px "+(d?d:"")}
function ca(a,b,c,d){J=document.getElementById(a);K=document.getElementById(b);L=document.getElementById(c);M=document.getElementById(d);if(!(J&&K&&L&&M))return T=g;P=O=g;y=[];z=[];R=google.getComputedStyle(document.getElementById("sbc"),"height")-1;S=google.getComputedStyle(M,"height");a=[J,K,L];for(b=0;c=a[b++];){google.bind(c,"mouseover",function(e){$(e.target)});google.bind(c,"mouseout",function(e){$(e.target,f)});c.onmousedown=function(){return g};
}google.bind(J,"mousedown",function(){W(f);X(f)});google.bind(K,"mousedown",function(){W(f);X()});google.bind(L,"mousedown",function(e){W(f);N=e.clientY;google.bind(document,"mousemove",Z)});return T=f}
google.bind(document,"mouseup",function(){document.removeEventListener("mousemove",Z,g);W(g)});google.dstr.push(function(){y=z=[];T=g});
var ka=/(\d+) (\u0441\u0435\u043a|\u043c\u0438\u043d|\u0447\u0430\u0441)\.? \u043d\u0430\u0437\u0430\u0434/,la=["\u044f\u043d\u0432\u0430\u0440\u044f","\u0444\u0435\u0432\u0440\u0430\u043b\u044f","\u043c\u0430\u0440\u0442\u0430","\u0430\u043f\u0440\u0435\u043b\u044f","\u043c\u0430\u044f","\u0438\u044e\u043d\u044f","\u0438\u044e\u043b\u044f","\u0430\u0432\u0433\u0443\u0441\u0442\u0430","\u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044f","\u043e\u043a\u0442\u044f\u0431\u0440\u044f","\u043d\u043e\u044f\u0431\u0440\u044f",
"\u0434\u0435\u043a\u0430\u0431\u0440\u044f"],ma=-1;function na(a,b){var c=a.innerHTML.match(ka);if(c&&c.length==3){var d=parseInt(c[1],10)||0;d*=c[2]=="\u0441\u0435\u043a"?1:c[2]=="\u043c\u0438\u043d"?60:c[2]=="\u0447\u0430\u0441"?3600:0;a.timestamp=b-d}else if(a.innerHTML=="\u0442\u043e\u043b\u044c\u043a\u043e \u0447\u0442\u043e")a.timestamp=b-30}function I(){return Math.round((new Date).getTime()/1E3)}
function oa(a,b){if(a.timestamp){b=b-a.timestamp;if(b<45)b="\u0442\u043e\u043b\u044c\u043a\u043e \u0447\u0442\u043e";else if(b<105)b="1 \u043c\u0438\u043d. \u043d\u0430\u0437\u0430\u0434";else if(b<3345){b=Math.floor(b/60)+(b%60>=45?1:0);b=b+" \u043c\u0438\u043d. \u043d\u0430\u0437\u0430\u0434"}else if(b<6600)b="1 \u0447\u0430\u0441 \u043d\u0430\u0437\u0430\u0434";else if(b<84300){b=Math.floor(b/3600)+(b%3600>=3E3?1:0);b=b+" \u0447\u0430\u0441. \u043d\u0430\u0437\u0430\u0434"}else{b=new Date(a.timestamp*
1E3);b=b.getDate()+" "+la[b.getMonth()]+", "+b.getFullYear()}a.innerHTML=b}}function pa(a){var b=[];a=a.getElementsByTagName("span");for(var c=0,d;d=a[c++];)d.className.match("rtd")&&b.push(d);return b}function H(a,b,c){a=pa(a);c=c||I();for(var d=0,e;e=a[d++];)b?na(e,c):oa(e,c)}function fa(a){a=pa(a);a.length>0&&na(a[0],I())}function ba(a){H(a,f);ma=window.setInterval(function(){H(a)},6E4)}google.dstr.push(function(){window.clearInterval(ma)});})();
(function(){google.eggRequest=function(a){var b=document.createElement("SCRIPT");b.src="http://clients1.google.com/egg?ei="+google.kEI+"&cd="+a;google.append(b)};!google.neegg&&document.f&&document.f.btnI&&google.bind(document.f.btnI,"click",function(a){if(google.sn=="webhp"&&!google.neegg&&document.f.q.value==""){google.eggRequest("ifl");a.stopPropagation&&a.stopPropagation();a.cancelBubble=true;a.preventDefault&&a.preventDefault();return a.returnValue=false}});})();
(function(){google.Tbpr={};var b={persisted:false,lastClicked:-1},c;function g(){c={};for(var a=document.getElementsByTagName("h3"),e=0,d;d=a[e++];)if(d.className=="tbpr")c[d.id]=d}function h(){for(var a in c)c[a].style.display="none"}function i(a){a="tbpr_"+a;if(c[a])c[a].style.display=""}function j(){h();var a="/gen_204?atyp=i&ct=backbutton&ei="+google.kEI;if(b.lastClicked>=0){a=a+"&idx="+b.lastClicked;i(b.lastClicked)}window.google.log("backbutton","a",a)}
function k(a){return function(){b.lastClicked=a;google.History.save(l,b)}}function m(){g();for(var a=0,e=document.getElementsByTagName("a"),d=0,f;f=e[d++];)if(f.className=="l"){a++;var n="tbpr_"+a;google.bind(f,"click",k(c[n]==null?-1:a))}}function o(){b.persisted=true;google.History.save(l,b)}function p(a){if(a.persisted&&(!google.j||!google.j.en))j()}google.Tbpr.init=function(){m();o();window.addEventListener&&window.addEventListener("pageshow",p,false)};
var l=google.History.client(function(a){b.persisted=a.persisted;b.lastClicked=a.lastClicked;b.persisted&&j()});})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];
(function (){if(window.google){window.google.a={};window.google.c=1;function k(a,b,d){b=a.t[b];a=a.t.start;if(b&&(a||d)){if(d!=undefined)a=d;return b>a?b-a:a-b}}window.google.report=function(a,b,d){var f="";if(window.google.pt){f+="&srt="+window.google.pt;delete window.google.pt}var c=document.getElementById("csi");if(c){var e;if(window.google._bfr!=undefined)e=window.google._bfr;else{e=c.value;window.google._bfr=e;c.value=1}if(e)return""}if(a.b)f+="&"+a.b;if(window.parent!=window)f+="&wif=1";c=a.t;e=c.start;
var h=[];for(var g in c)g!="start"&&e&&h.push(g+"."+k(a,g));delete c.start;if(b)for(var i in b)f+="&"+i+"="+b[i];a=[d?d:"/csi","?v=3","&s="+(window.google.sn||"GWS")+"&action=",a.name,f,"&rt=",h.join(",")].join("");b=new Image;var j=window.google.c++;window.google.a[j]=b;b.onload=b.onerror=function(){delete window.google.a[j]};b.src=a;b=null;return a}};if(google.timers&&google.timers.load.t){if(!google.nocsixjs)google.timers.load.t.xjsee=google.time();window.setTimeout(function(){if(google.timers.load.t){google.timers.load.t.xjs=google.time();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0)};})();
